lib/mix/tasks/heroicons/generate.ex
lib/petal_components/icons/heroicons/outline.ex
lib/petal_components/icons/heroicons/solid.ex

According to the Heroicons website, the solid icons are supposed to use `w-5 h-5` and the outline icons use `w-6 h-6`.
This PR fixes this discrepancy, and also introduces a sort in the mix task when generating the modules, so that future re-generations don't cause unnecessary churn in the diffs (sorry this one is so big...).  I also re-generated using Heroicons `v1.0.3`.

Solid Heroicons are meant to be w-5 h-5

---

lib/petal_components/table.ex
test/petal/table_test.exs

Ran into this while trying to hide table columns on a small screen. It's possible to hide `<td>` elements but it didn't
work for `<th>`. This patch makes sure to forward the `class` assign to every component in `PetalComponenets.Table`.

Forward class attribute to table components

---

lib/petal_components/pagination.ex

The pagination had some issues on gray backgrounds and in dark mode.
Before:
After:

Update pagination on gray backgrounds

---

.github/workflows/ci.yml

This is a proposal for a GitHub Workflow to run test on every push. It does:
* Checkout the source
* Set up OTP and Elixir for a matrix of versions, currently the two most recent release branches (the `mix.exs` for
Petal Components states compatibility with Elixir 1.12 and higher)
* Get dependencies
* Run tests

Add a CI action

---

lib/petal_components/tabs.ex

Noticed that `<.tab class="some-class" />` doesn't work yet, this fixes it.

Fixed passing :class to tab

---

lib/petal_components/form.ex
test/petal/progress_test.exs

- Do not leak the `class` assign as it's already set from `classes`
- Fix tests

Do not accidentally override form classes

---

lib/petal_components.ex
lib/petal_components/slide_over.ex
test/petal/slide_over_test.exs

This introduces a basic SlideOver component adapted from the existing Modal.
TODO:
- Work out how to handle max-height/max-width, if at all.
- Add RTL/writing mode support.
- Make any further changes as requested by the Petal components core developers.
Some gifs:
Mobile view:
Desktop view:

Begin adding SlideOver component

---

lib/petal_components/button.ex

Using `inline-block` avoids linebreaks inside the icon buttons when
not using a button (e.g. `<a>`).

Use `inline-block` for icon buttons

---

lib/petal_components/alert.ex
lib/petal_components/avatar.ex
lib/petal_components/badge.ex
lib/petal_components/button.ex
lib/petal_components/card.ex
lib/petal_components/class.ex
lib/petal_components/container.ex
lib/petal_components/form.ex
lib/petal_components/link.ex
lib/petal_components/loading.ex
lib/petal_components/modal.ex
lib/petal_components/pagination.ex
lib/petal_components/slide_over.ex
lib/petal_components/table.ex
lib/petal_components/tabs.ex
lib/petal_components/typography.ex
test/petal/class_test.exs
test/petal/link_test.exs
test/petal/table_test.exs

`build_class/2` is basically `Enum.join/2` with some improvements
for building the class names. For example empty strings are not joined
into the class names and the default joiner is set to a single whitespace to avoid specifying it every time.
Before:
After:

Generate prettier classes

---

lib/petal_components/form.ex

The form switch component is currently using a hardcoded colour blue rather than the configured primary colour.

Switch should use primary colour instead of blue

---

lib/mix/tasks/heroicons/generate.ex
lib/petal_components/class.ex
lib/petal_components/icons/heroicons/outline.ex
lib/petal_components/icons/heroicons/solid.ex
test/petal/heroicons_test.exs

In 538f2b1348e31537b6f41d68b044d5655d2edd2e the docs for the Heroicons component were updated to use `type="icon_name"` instead of `icon={:icon_name}`:
```heex
<PetalComponents.Heroicons.Solid.render icon={:home} class="w-6 h-6" />
<PetalComponents.Heroicons.Solid.render type="home" class="w-6 h-6" />
```
But it doesn't work since the render function wasn't updated.

Fix heroicons render method

---

lib/petal_components/button.ex
lib/petal_components/dropdown.ex
lib/petal_components/pagination.ex
lib/petal_components/tabs.ex
test/petal/form_test.exs
test/petal/link_test.exs

The next version of liveview introduces a `link` component, not sure if this can be used here, but this PR makes it compatible with the next version by not importing the `Link` module.
Fixes #42

Make compatible with liveview 0.18

---

lib/petal_components/form.ex

Checking the length of the list means always traversing the whole list,
matching on the empty list is (in this case marginally) faster, and more
idiomatic.

fixed field_has_errors?

---

lib/petal_components/modal.ex

Seems related to #30 and some recent changes that were added to support modals in components. As-is, this was still sending the `close_modal` event to the LiveView page when used inside a component and a specific target is passed, as well as to the target. This'll make it so only the target gets the event

Only send close_modal event to target if provided

---

lib/petal_components/slide_over.ex

The `SlideOver` component was using the modal overlay/content IDs `modal-overlay` and `modal-content`. Now it is an edge case, but if you had both a `SlideOver` and a `Modal` opened, then closing the `Modal` would cause the `SlideOver` to disappear as well (but without any user interaction possible in the area that was covered by the `SlideOver`).
To fix this, these IDs are now `slide-over-overlay` and `slide-over-content`. A truly "perfect" solution would generate an ID per instance of `SlideOver`/`Modal` that is on the page, such that multiple modals/slideovers are can be present on a single page.
Tests are not included, since proper testing depends on executing javascript.

Fix 'modal' IDs used at SlideOver component

---

lib/mix/tasks/heroicons/generate.ex
lib/petal_components/form.ex
lib/petal_components/icons/heroicons/outline.ex
lib/petal_components/icons/heroicons/solid.ex
test/petal/heroicons_test.exs

In #44 I fixed the render method for heroicons to work with strings. Before the names of the icons were atoms and the dashes in their names were replaced with underscores, but since we're using strings now there is no reason to use underscores.
This PR uses `String.replace` to replace all "-" with "_" before calling the function which makes the names from heroicons.com work out of the box, but icon names with underscores should keep working.
Edit: 
Regarding the atoms existing in the last PR
> I just assumed they were since module names are atoms too, and it seems to work (I tested it with a project that uses a lot of different icons and they all showed up correctly using the new syntax for render).
Function names do not count as atoms. I think they all exist because they are created in …

Allow heroicon names containing "-"

---

lib/petal_components/pagination.ex
lib/petal_components/pagination_internal.ex
test/petal/pagination_test.exs

or boundary_count less than 1.
if boundary count is set to zero, no ellipsis or boundary pages are shown.
if sibling count is set to zero only the current page is shown.
if total_pages is 1 or less only the button for page one is shown.
The behavior is such that the number of page buttons shown is always `boundary_count * 2 + sibling_count * 2 + 1`
unless the total_pages count doesn't allow for that.
If this pull request need work, please let me know.

Fixed pagination control if users set sibling_count to less than 1

---

lib/petal_components/pagination.ex
test/petal/pagination_test.exs

Allows the Pagination component to receive a function as a parameter that will define the path of the page.
This change will bring flexibility so that we can use helper functions like the [Phoenix Routing](https://hexdocs.pm/phoenix/routing.html#path-helpers) ones to generate the path:  
```elixir
<.pagination path={fn page -> Routes.user_path(Endpoint, :index, [page: page]) end} current_page={1} total_pages={10} />
```
> The above function should dynamically generate the path `/users?page=#{page}`.

Accepts function to define the path in Pagination component

---

lib/petal_components/form.ex

Added a better background color for disabled fields in dark mode and also removed a duplicate `dark:border-gray-600` for select fields.

Fix background color for disabled fields in dark mode

---

lib/petal_components/form.ex
test/petal/form_test.exs

To resolve #103. Adds ability to add help text to form fields. Inline, you can do the following.
```elixir
<.form_help_text help_text="Help text" />
```
Here's the same example, but using a slot (so you can add more than text):
```elixir
<.form_help_text>
Help text<br />
With some html
</.form_help_text>
```
Finally, you can add `help_text` to `form_field` (at this stage, there is no slot option):
```elixir
<.form_field
type="text_input"
form={f}
field={:text_input}
placeholder="Placeholder"
help_text="Help text"
/>
```

Form help text

---

lib/petal_components/form.ex

Hello,
I have tried to upgrade petal_components to 0.19.x in my project
the following code:
```elixir
<.form :let={f} for={:user}>
<.text_input form={f} field={:city} list="cities" />
<datalist id="cities">
<%= for city <- ["New York", "London"] do %>
<option value={city}><%= city %></option>
<% end %>
</datalist>
</.form>
```
produce the following warning:
```
warning: undefined attribute "list" for component PetalComponents.Form.text_input/1
```
it is a warning doesn't break anything but with `warnings_as_errors` option enabled it can be blocking
not sure how to add a unit test for this thing

Add missing `list` attr to form input

---

lib/petal_components/badge.ex

The private function `get_color_classes` had some fairly redundant pattern matching. Given that the badge component constrains the incoming attribute already, it seems safe to skip the pattern matching that was being performed in favor of simpiler, more readable code.
Of course, please let me know if I've misunderstood something.

Minor code readability improvement for Badge component

---

CHANGELOG.md
lib/petal_components/button.ex
test/petal/button_test.exs

An icon button sometimes isn't very useful as the user might recognise what it is or does. So let's allow for a tooltip.
This is what it looks like:

Add tooltip to `icon_button`

---

assets/default.css
lib/petal_components/button.ex
test/petal/button_test.exs

- Add fade-in transition to make it nicer
- Remove the unneeded `label`
- Make it more portable by self-contain the `flex` class
- Make the grouping isolated so it can be nested in parent groups

Tooltip tweaks

---

lib/petal_components/form.ex

Currently, when nothing's checked it produces this param:
```elixir
"tags" => ""
```
In this case, tags should be an array, so this fix makes it:
```elixir
"tags" => [""]
```

Fix the empty value for a checkbox group

---

assets/default.css

Make progress bars look nicer in dark mode

---

lib/petal_components/field.ex

Please feel free to close this PR, but I was hoping v2 and v1's default styling are consistent. So adding `rows="4"` to match v1's.

Make textarea v2's height the same as v1

---

lib/petal_components/field.ex

So the radio group doesn't actually remember the state, so this PR fixes it.
However, there are currently no tests to test the form's state behaviour, I'm not sure what the best way to do it is. @mplatts @nhobes

Fix radio group's state

---

CHANGELOG.md
RELEASE.md
lib/petal_components/button.ex
test/petal/button_test.exs

Ported the same tooltip from `icon_button` to `button`.

Add `tooltip` to `<.button>`

---

assets/default.css
lib/petal_components/field.ex
test/petal/field_test.exs

When there's no options it'll be great if we could add a message (different to error label).

Add `empty_message` attr for `checkbox-group` and `radio-group`

---

assets/default.css

This PR fixes the bg colour of the checked checkboxes.
Dark mode works fine:
However, light mode currently looks like this, note that the first three boxes are checked, the last one is not, but they all look the same:
With this PR:
Took me a while to realise this was caused by styling. I was going crazy thinking my auto-checking plugin was broken. 🙈

Fix bg colour for input checkbox

---

lib/petal_components/field.ex
lib/petal_components/form.ex
lib/petal_components/input.ex

Prevent showing warnings for supported fields `autocapitalize` and `autocorrect` for input fields.
https://davidwalsh.name/disable-autocorrect

Add support for autocorrect and autocapitalize props in input fields

---

lib/petal_components/accordion.ex

Following up on Issue https://github.com/petalframework/petal_components/issues/229, here's what I came up with. This takes advantage of the new naming convention to allow for new styles that are intended for the last item only. As described in the issue, the main use case I had in mind when wanting this was rounding the bottom of the accordion to allow for a fully border-radius'd appearance instead of rounded on top and flat on bottom. The problem is that sometimes the bottom of the table is the last accordion button itself and sometimes it's the last accordion item's content box. (Guessing this is why the accordion was made flat on the bottom to begin with)
This PR doesn't explicitly add styles for rounding the table by default, but it adds logic to apply an always on class: …

Add support for styling last accordion item

---

lib/petal_components/pagination.ex
test/petal/pagination_test.exs

This PR adds the `event` flag to the pagination component. If enabled, the `link_type` and `path` options will be overwritten, and clicking the buttons in the component will send events to the parent LiveView. Here's an example:
```heex
<.pagination event={true} current_page={@page} total_pages={@total_pages} />
```
```elixir
@impl true
def handle_event("goto-page", %{"page" => page}, socket) do
{:noreply, push_patch(socket, to: ~p"/posts/#{page}")}
end
```
This PR is a replacement for #240

 Add option to send events in pagination component

---

lib/petal_components/button.ex
test/petal/button_test.exs

Description
---
The info color arg for icon buttons was being set to the primary class. This PR just makes this small fix and adds some test coverage to ensure the colors are set correctly.

Fix: Icon button setting info to primary

---

lib/petal_components/slide_over.ex

Ideally `button` elements should always specify a `type` attribute to avoid unexpected behavior, since each browser might implement a different default.
In our app, we do HTML forms inside slide overs. When the user clicks to close a slide over, the form ends up being submitted, given that the close button is inside the form. Setting the button's type prevents this issue.

Add `type=button` to close slide over button

---

assets/default.css
lib/petal_components/button.ex
lib/petal_components/dropdown.ex
lib/petal_components/link.ex
lib/petal_components/rating.ex
test/petal/dropdown_test.exs

Hi! I added support for the `disabled` attribute on the `dropdown_menu_item` component.
I don't know whether this is the correct way to apply styling. I tried to mirror the approach that the `button` component uses.
Also, sorry for the giant diff! I removed the annoying brackets the formatter adds everywhere. Btw, that has been fixed a while ago in ElixirLS, see elixir-lsp/elixir-ls#526.

Add support for disabled attribute on dropdown menu items

---

lib/petal_components/pagination.ex
test/petal/dropdown_test.exs
test/petal/pagination_test.exs

In #241 I added an option to make the pagination component send events instead of using `live_patch`/`live_redirect`. 
This PR adds an optional `target` option, that can be used to set the `phx-target` for those events, which makes it also work in LiveComponents :)

Add `target` attribute for sending pagination events to LiveComponents

---

lib/petal_components/tabs.ex

Sorry for the delay on this, following up on the quick change referenced in https://github.com/petalframework/petal_components/issues/254. Passes through a `disabled` attribute to the `Link` component for `Tab`s.
(I also fixed a small doc typo I noticed while I was in there for the underline attribute.)

Add `disabled` attribute to Tab component

---

assets/default.css
lib/petal_components/pagination.ex
test/petal/pagination_test.exs

Adds a boolean attribute to the pagination component allowing the previous & next buttons to always be shown on the boundary pages. Defaults to current behavior (prev not shown on page 1, next not shown on last page).
Buttons shown on those boundary pages are disabled and reduced opacity.
[Loom of the live boilerplate page](https://www.loom.com/share/15f0d94008874bc58ae7cc007fe41a7a?sid=59d436c3-537c-4c4f-b933-fade87bb7dfe)
Resolves #140

Add pagination attribute allowing always shown prev and next buttons

---

lib/petal_components/pagination.ex
test/petal/pagination_test.exs

Following #262 
Finally it's not a good idea to encode the path first you have to split the query from the path and encode.
Something like
```
uri = URI.new!("/team?page=:page")
iex(7)> URI.decode_query(uri.query)
%{"page" => ":page"}
iex(8)> query = URI.decode_query(uri.query) |> URI.encode_query()
"page=%3Apage"
iex(9)> %{uri | query: query} |> to_string()
""/team?page=%3Apage""
```
Instead I use a simple regex with a OR.

Pagination support encoded path

---

assets/default.css
lib/petal_components/breadcrumbs.ex
test/petal/breadcrumbs_test.exs

To add support for optional icon for the links shown in breadcrumbs component.

Add icon support to breadcrumb link

---

lib/petal_components/slide_over.ex

Add the `close_on_click_away` and `close_on_escape` attributes to the `slideover` so it matches the `modal`
I was chatting with @mplatts about adding the `close_on_click_away` attr yesterday, but since we are here i also added the `close_on_escape` as well giving more flexibility to the component 🙂
lmk if i'm missing anything ❤️

Add 'close on' attributes to slideover

---

lib/petal_components/modal.ex
test/petal/modal_test.exs

Currently, the `class` passed into the modal component is part of the `rest` global attr, since it's not explicitly declared, which causes `custom_classes` in `get_classes/1` to always be `""`.

Fix modal class

---

lib/petal_components/table.ex
test/petal/table_test.exs

State with data:
State without data ("empty state"):
Add optional empty states for tables. 
* named slot `:empty_state` 
* always rendered at the top of the table into a cell that spans the whole width (the width is derived from the number of `:col` slots supplied)
* the row that holds the cell has `hidden only:table-row` Tailwind classes so it's only visible if it's the _only_ row
* the slot takes `row_class` that is then forwarded to the cell
* renders multiple cells if more than one `:empty_state` slot is given <- I'm not entirely sure about this, maybe we
should rather crash if more than one slot is set?

Add support for empty states in tables

---

lib/petal_components/dropdown.ex

I added a `phx-` attribute for hiding dropdown menus when pressing the escape key.

Hide dropdown when pressing escape

---

lib/petal_components/field.ex

The `for` attribute in `label` is supposed to match the `id` of a visible `input` element on the page. 
Since the `radio-group` component renders multiple `radio` inputs, it's not possible to have the label match a single element with a unique ID.
Having the `label` unmatched with an `input` causes an accessibility issue to show up on the Chrome dev tools.

Remove `for` attribute in `radio-group` label

---

lib/petal_components/field.ex
lib/petal_components/menu.ex
lib/petal_components/skeleton.ex
test/petal/field_test.exs
test/petal/menu_test.exs

Also, avoid creating a `label` that does not refer to a legitimate `input` element - removes warning.
See https://github.com/petalframework/petal_components/issues/328 for original change to radio-group

Remove for attribute in checkbox-group label

---

lib/petal_components.ex
lib/petal_components/accordion.ex
lib/petal_components/dropdown.ex
lib/petal_components/menu.ex

This PR adds `default_js_lib/0` to address the inconvenience of having to set `js_lib` for the component every time it is used.

Add default_js_lib config

---

lib/petal_components/form.ex
test/petal/form_test.exs

Following on from PR https://github.com/petalframework/petal_components/pull/336 and PR https://github.com/petalframework/petal_components/pull/333, this removes errors/warnings for date and time select form components

Use `spans` instead of `labels` if there is no `for` attribute

---

lib/petal_components/icon.ex
mix.exs

The `:heroicons` dependency cannot be part of deployment to hex (you can't include a dependency that refers to a GitHub repo). So I've adjusted the code to work when there is no `:heroicons` dependency/folder. The original code will still work in `:dev` mode or if the calling app includes the `:heroicons` dependency...

Generate list of heroicons if the dependency exists

---

lib/petal_components_web/a11y_live.ex

The a11y tests have been failing intermittently. @nhobes found [the culprit](https://github.com/angelikatyborska/a11y-audit-elixir/commit/b56c1439c680276c1e4972a9c4e6d879eec836b0). This implements the fix outlined there.

Ensure css transitions don't cause flaky tests

---

assets/default.css

* Heroicon placeholder is inside a `span` so colour is controlled by the background (not foreground)
* Adds `!important` so that margin works

Addresses positioning and dark mode for avatar

---

lib/petal_components.ex
lib/petal_components/button_group.ex
lib/petal_components_web/a11y_live.ex
test/petal/button_group_test.exs

API example:
```heex
<.button_group aria_label="Size options" size={@group_size}>
<:button phx-click="change_size" phx-value-size="xs">XS</:button>
<:button phx-click="change_size" phx-value-size="sm">SM</:button>
<:button phx-click="change_size" phx-value-size="md">MD</:button>
<:button phx-click="change_size" phx-value-size="lg">LG</:button>
<:button phx-click="change_size" phx-value-size="xl">XL</:button>
</.button_group>
```
https://github.com/user-attachments/assets/a4131347-3901-4d9f-9ff1-25ad0319643c

implement button_group/1 component

---

lib/petal_components/table.ex

Running tests on an app that passes stream to the table component produces the following error:
```
** (ArgumentError) setting phx-update to "stream" requires setting an ID on each child. No ID was found on:
<tr class="pc-table__tr hidden only:table-row"><td class="pc-table__td " colspan="2">
```
because the row that contains the empty state slot has no ID.
Based on https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#stream/4-handling-the-empty-case, the row with the empty state should also have an ID.
Versions used:
elixir          1.17.2-otp-27
phoenix_live_view          0.20.14

Add ID to table row containing empty state slot

---

lib/petal_components/slide_over.ex

When closing the slide over component, the main wrapper's `display: block` rule from `JS.show` doesn't get removed, leading to underlying content being blocked.
This PR fixes it by also hiding the wrapper at the other end of the chain.

Fix slide-over wrapper/overlay not hiding on close

---

lib/petal_components/button_group.ex
lib/petal_components/dropdown.ex

Address Button Group warnings

---

assets/default.css

fixes the date input icon overlap on safari. 
https://github.com/petalframework/petal_components/issues/372
the issue - 
the fix -

fix the date inputs icon overlap in safari 

---

assets/default.css

CSS to fix size of datetime inputs in Safari.

---

lib/petal_components/slide_over.ex
test/petal/slide_over_test.exs

The `slide_over` component has a number of elements with the `id` set. These elements need an `id` so the show/hide animations work. However, if you want to include more than one `slide_over` in a single page, then these ids end up creating a name conflict.
This PR adds an `id` attribute - allowing the ids to be user configurable. Therefore allowing more than one `slide_over` per page

Allow for multiple instances of the `slide_over` component

---

README.md
assets/default.css
lib/petal_components/user_dropdown_menu.ex

Petal Component classes have been moved into the `components` layer. 
The `.skeleton` class was being used like a utility class - but rather than turning it into one, I opted to be un-DRY. I think if we create `@utility` classes, that should be in the future with the appropriate consideration.  
I've followed the recommendations found in the Tailwind documentation (i.e. removed or renamed utilities):
https://tailwindcss.com/docs/upgrade-guide
I also used the changes in  https://github.com/petalframework/petal_components/pull/411 to compare my work. Thanks @IdoLeshkowitz!

Prepare Petal Components for Tailwind 4

---

lib/petal_components/field.ex

the hidden input on the checkbox group had a different name then the other inputs on the group - which caused issues with the `used_input?` mechanism. 
attaching an example to reproduce the issue, it has a simple form with a checkbox group, text input and a `used_input?` boolean indicator binded to the checkbox field. go ahead and type something into the text input. 
The `used_input?` indicator will change to false. 
```elixir
Mix.install([
{:phoenix_playground, "~> 0.1.6"}, 
{:petal_components, "~> 2.8"}, 
{:phoenix_live_view, "~> 1.0"}
])
defmodule DemoLive do
use Phoenix.LiveView
use PetalComponents
def mount(_params, _session, socket) do
form = to_form(%{"checkbox" => nil, "text" => nil})
{:ok, assign(socket, form: form)}
end
def handle_event("validate", params, socket) do 
form = …
```

Fix hidden `checkbox-group` input name

---

assets/default.css

* Light button text wasn't right on hover (in dark mode)
* Table dividers set to `border-gray-200` instead of `currentColor`
* Removed some unnecessary classes

Address CSS anomolies after Tailwind 4 upgrade

---

lib/petal_components/field.ex

**Current behavior**
Clearable form field does not trigger form's `phx-change` when clicking the clear button and the LiveView doesn't receive the updated form state.
**Expected behavior**
`phx-change` is triggered on the form just as it is when typing in something in the input.
**Fix**
Updated the clear button logic to dispatch the 'input' event with `{ bubbles: true }`, allowing the event to propagate up to the form and properly trigger `phx-change`.

Bubble event when input is cleared
